### ISSUE TITLE
Add ability to plot ellipses

### ISSUE THREAD

**Issue by wmwv** [LSSTDESC/skyproj#27]
I'd like to add the ability to plot ellipses.  The path forward seems to be to add and `skyaxes.ellipse` function next to the `skyaxes.circle` function 

https://github.com/LSSTDESC/skyproj/blob/d46052ee9cda7277b06bcc008ea022ba66518757/skyproj/skyaxes.py#L233

The key is then to figure out what the `dist` argument should be as a function of `az` in the call to `geod.fwd`

Does the following seem basically right?

```
    def circle(self, lon, lat, radius, nsamp=100, fill=False, **kwargs):
[...]
        az = np.linspace(360.0, 0.0, nsamp)
        lons, lats, _ = geod.fwd(
            np.full(nsamp, lon, dtype=np.float64),
            np.full(nsamp, lat, dtype=np.float64),
            az,
            np.full(nsamp, radius_m)
        )
```

```
    def ellipse(self, lon, lat, a, b, theta, radius, nsamp=100, fill=False, **kwargs):
[...]
        az = np.linspace(360.0, 0.0, nsamp)
        pa_offset = 90  # Position Angle is defined as degrees East of North
        pa_offset_in_radians = np.deg2rad(pa_offset)
        phase_in_radians = np.deg2rad(az - theta - pa_offset)

        theta_in_radians = np.deg2rad(theta)
        rotated_x = a * np.cos(phase_in_radians)
        rotated_y = b * np.sin(phase_in_radians)
        x = rotated_x * np.cos(theta_in_radians - pa_offset_in_radians) - rotated_y * np.sin(theta_in_radians - pa_offset_in_radians)
        y = rotated_x * np.sin(theta_in_radians - pa_offset_in_radians) + rotated_y * np.cos(theta_in_radians - pa_offset_in_radians)
        dist = np.sqrt(x**2 + y**2)
        lons, lats, _ = geod.fwd(
            np.full(nsamp, lon, dtype=np.float64),
            np.full(nsamp, lat, dtype=np.float64),
            az,
            dist,
        )
```

**Comment by wmwv** [comment]
Oh, and you would need to convert

a_m = RADIUS * np.deg2rad(a)
b_m = RADIUS * np.deg2rad(b)

and use those in calculating x, y (or `rotated_x` and `rotated_y` in the above snippet).

**Comment by erykoff** [comment]
Ooh, clever!  If you want to make a PR you are welcome.  Or I can incorporate this into my next update which is overhauling the way that RADIUS is used because right now it can get out of sync.

**Comment by wmwv** [comment]
Great.  I'll make  PR.

**Comment by wmwv** [comment]
In case anyone from the future reads this Issue, my proposed math was wrong.  The correct answer for calculating the dist=r(theta) for the ellipse is

```
        # Position Angle is defined as degrees East from North
        phase_rad = np.deg2rad(az - theta)
        denom = np.sqrt((b_m * np.cos(phase_rad))**2 + (a_m * np.sin(phase_rad))**2)
        dist = a_m * b_m / denom
```
