### ISSUE TITLE
Image filesize blows up when using set_extent

### ISSUE THREAD

**Issue by DhayaaAnbajagane** [LSSTDESC/skyproj#53]
I was plotting some healsparse maps with skyproj, and found some interesting behavior in the filesize of the figure's saved PDF. I am using `skyproj.McBrydeSkyproj` object to plot a map of the DELVE region (~180 degrees RA away from DES) and show only a subset of the sky around and including the footprint.

If I initialize the Skyproj object and pass in an `extent = [....]` input specifying the region to plot, then the resulting PDF of the figure is couple of KBs as expected. If I instead don't pass in `extent` during object initialization, and set it afterwards using the `skyproj.set_extent(...)` routine, then the filesize is multiple MBs. I copy a minimal working example below. I seem to have isolated this to where the `extent` information is specified: during initialization or if its done afterwards. The latter causes the big filesize. From what I can tell by viewing the PDFs, it seems using `set_extent()` is changing the rasterization behavior, where the output PDF is not rasterized.

```
import numpy as np
import matplotlib.pyplot as plt
import healpy as hp
import healsparse as hsp
import skyproj
import os

#Make an example map
NSIDE = 128

M = np.zeros(hp.nside2npix(NSIDE))

ra, dec = hp.pix2ang(NSIDE, np.arange(M.size), lonlat = True)
mask    = (ra > 100) & (ra < 200) & (dec < 30) & (dec > -45)

M[mask] = 1
M = hsp.HealSparseMap(healpix_map = M, nest = False, sentinel = 0., nside_coverage = 128, )


#Regular plotting
sp = skyproj.McBrydeSkyproj(lon_0 = 180, extent = [100, 270, -49, 35])
im = sp.draw_hspmap(M, cmap = 'magma_r', zoom = False, rasterized = True,)

plt.savefig('./tmp1.pdf', dpi = 300, bbox_inches = 'tight')
plt.close()


#Regular plotting but extent is changed after drawing/init
sp = skyproj.McBrydeSkyproj(lon_0 = 180,)
im = sp.draw_hspmap(M, cmap = 'magma_r', zoom = False, rasterized = True,)

sp.set_extent([100, 270, -49, 35])
plt.savefig('./tmp2.pdf', dpi = 300, bbox_inches = 'tight')
plt.close()



size_reg = os.path.getsize('./tmp1.pdf')
size_set_extent = os.path.getsize('./tmp2.pdf')

print("WITH EXTENT IN INIT %0.2f MB" % (size_reg/1e6))
print("WITH SET_EXTENT AFTER INIT %0.2f MB" % (size_set_extent/1e6))
```

These are my version details:

```
hsp ver: 1.7.0
skyproj ver: 1.2.0
mpl ver: 3.7.1
```

**Comment by erykoff** [comment]
Thank you very much for your detailed bug report and repro!  I think I see the problem and this should be a quick fix, and I will get to it asap.  In the meantime, if you either set the extent prior to drawing the map, or doing `lon_range=` and `lat_range=` when drawing the map you will avoid this bug.  If you are saving the figure and then zooming (for example) you'd have to make a new figure.
