### ISSUE TITLE
Using normalization of the map

### ISSUE THREAD

**Issue by xuod** [LSSTDESC/skyproj#55]
It would like to visualize a HealSparse map with a logarithmic scale, however `pcolormesh` does not accept the `norm` kwarg as skyproj already passes `vmin` and `vmax`.

Minimum example
```
fig = plt.figure(figsize=(6,6))
ax = fig.add_subplot(111)
sp = skyproj.HammerSkyproj(ax=ax)
_ = sp.draw_hspmap(hsp, norm=mpl.colors.LogNorm())
```
raises
`ValueError: Passing a Normalize instance simultaneously with vmin/vmax is not supported.  Please pass vmin/vmax directly to the norm when creating it.
`

This uses Matplotlib 3.7.2 and skyproj 1.0.3.

**Comment by erykoff** [comment]
Fixed with #57
